// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: role_action.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RoleDetail struct {
	RoleID               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleDescription      string   `protobuf:"bytes,3,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	RoleManagerDomain    string   `protobuf:"bytes,4,opt,name=role_manager_domain,json=roleManagerDomain,proto3" json:"role_manager_domain,omitempty"`
	RoleAlias            string   `protobuf:"bytes,5,opt,name=role_alias,json=roleAlias,proto3" json:"role_alias,omitempty"`
	IsActive             bool     `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleDetail) Reset()         { *m = RoleDetail{} }
func (m *RoleDetail) String() string { return proto.CompactTextString(m) }
func (*RoleDetail) ProtoMessage()    {}
func (*RoleDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{0}
}
func (m *RoleDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDetail.Unmarshal(m, b)
}
func (m *RoleDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDetail.Marshal(b, m, deterministic)
}
func (m *RoleDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDetail.Merge(m, src)
}
func (m *RoleDetail) XXX_Size() int {
	return xxx_messageInfo_RoleDetail.Size(m)
}
func (m *RoleDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDetail.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDetail proto.InternalMessageInfo

func (m *RoleDetail) GetRoleID() uint32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *RoleDetail) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RoleDetail) GetRoleDescription() string {
	if m != nil {
		return m.RoleDescription
	}
	return ""
}

func (m *RoleDetail) GetRoleManagerDomain() string {
	if m != nil {
		return m.RoleManagerDomain
	}
	return ""
}

func (m *RoleDetail) GetRoleAlias() string {
	if m != nil {
		return m.RoleAlias
	}
	return ""
}

func (m *RoleDetail) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type GetRolesRequest struct {
	RoleIDs              string   `protobuf:"bytes,1,opt,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesRequest) Reset()         { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()    {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{1}
}
func (m *GetRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesRequest.Unmarshal(m, b)
}
func (m *GetRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesRequest.Marshal(b, m, deterministic)
}
func (m *GetRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesRequest.Merge(m, src)
}
func (m *GetRolesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolesRequest.Size(m)
}
func (m *GetRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesRequest proto.InternalMessageInfo

func (m *GetRolesRequest) GetRoleIDs() string {
	if m != nil {
		return m.RoleIDs
	}
	return ""
}

type GetRolesResponse struct {
	StatusCode           string        `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string        `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string        `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Roles                []*RoleDetail `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{2}
}
func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(m, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetRolesResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetRolesResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetRolesResponse) GetRoles() []*RoleDetail {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetRoleDetailRequest struct {
	RoleID               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleDetailRequest) Reset()         { *m = GetRoleDetailRequest{} }
func (m *GetRoleDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleDetailRequest) ProtoMessage()    {}
func (*GetRoleDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{3}
}
func (m *GetRoleDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleDetailRequest.Unmarshal(m, b)
}
func (m *GetRoleDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetRoleDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleDetailRequest.Merge(m, src)
}
func (m *GetRoleDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleDetailRequest.Size(m)
}
func (m *GetRoleDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleDetailRequest proto.InternalMessageInfo

func (m *GetRoleDetailRequest) GetRoleID() uint32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type GetRoleDetailResponse struct {
	StatusCode           string      `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string      `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string      `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	RoleDetail           *RoleDetail `protobuf:"bytes,4,opt,name=role_detail,json=roleDetail,proto3" json:"role_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRoleDetailResponse) Reset()         { *m = GetRoleDetailResponse{} }
func (m *GetRoleDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoleDetailResponse) ProtoMessage()    {}
func (*GetRoleDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{4}
}
func (m *GetRoleDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleDetailResponse.Unmarshal(m, b)
}
func (m *GetRoleDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetRoleDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleDetailResponse.Merge(m, src)
}
func (m *GetRoleDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoleDetailResponse.Size(m)
}
func (m *GetRoleDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleDetailResponse proto.InternalMessageInfo

func (m *GetRoleDetailResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetRoleDetailResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetRoleDetailResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetRoleDetailResponse) GetRoleDetail() *RoleDetail {
	if m != nil {
		return m.RoleDetail
	}
	return nil
}

type CreateRoleRequest struct {
	RoleName             string   `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleDescription      string   `protobuf:"bytes,2,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	RoleManagerDomain    string   `protobuf:"bytes,3,opt,name=role_manager_domain,json=roleManagerDomain,proto3" json:"role_manager_domain,omitempty"`
	RoleAlias            string   `protobuf:"bytes,4,opt,name=role_alias,json=roleAlias,proto3" json:"role_alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{5}
}
func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(m, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateRoleRequest) GetRoleDescription() string {
	if m != nil {
		return m.RoleDescription
	}
	return ""
}

func (m *CreateRoleRequest) GetRoleManagerDomain() string {
	if m != nil {
		return m.RoleManagerDomain
	}
	return ""
}

func (m *CreateRoleRequest) GetRoleAlias() string {
	if m != nil {
		return m.RoleAlias
	}
	return ""
}

type CreateRoleResponse struct {
	RoleID               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	StatusCode           string   `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,4,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleResponse) Reset()         { *m = CreateRoleResponse{} }
func (m *CreateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoleResponse) ProtoMessage()    {}
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{6}
}
func (m *CreateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleResponse.Unmarshal(m, b)
}
func (m *CreateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleResponse.Merge(m, src)
}
func (m *CreateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoleResponse.Size(m)
}
func (m *CreateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleResponse proto.InternalMessageInfo

func (m *CreateRoleResponse) GetRoleID() uint32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *CreateRoleResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *CreateRoleResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *CreateRoleResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type UpdateRoleRequest struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	RoleDescription      string   `protobuf:"bytes,3,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	RoleAlias            string   `protobuf:"bytes,4,opt,name=role_alias,json=roleAlias,proto3" json:"role_alias,omitempty"`
	RoleManagerDomain    string   `protobuf:"bytes,5,opt,name=role_manager_domain,json=roleManagerDomain,proto3" json:"role_manager_domain,omitempty"`
	RoleName             string   `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{7}
}
func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(m, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateRoleRequest) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *UpdateRoleRequest) GetRoleDescription() string {
	if m != nil {
		return m.RoleDescription
	}
	return ""
}

func (m *UpdateRoleRequest) GetRoleAlias() string {
	if m != nil {
		return m.RoleAlias
	}
	return ""
}

func (m *UpdateRoleRequest) GetRoleManagerDomain() string {
	if m != nil {
		return m.RoleManagerDomain
	}
	return ""
}

func (m *UpdateRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type UpdateRoleResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleResponse) Reset()         { *m = UpdateRoleResponse{} }
func (m *UpdateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleResponse) ProtoMessage()    {}
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{8}
}
func (m *UpdateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleResponse.Unmarshal(m, b)
}
func (m *UpdateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleResponse.Merge(m, src)
}
func (m *UpdateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleResponse.Size(m)
}
func (m *UpdateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleResponse proto.InternalMessageInfo

func (m *UpdateRoleResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *UpdateRoleResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *UpdateRoleResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type DeleteRoleRequest struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleRequest) Reset()         { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()    {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{9}
}
func (m *DeleteRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleRequest.Unmarshal(m, b)
}
func (m *DeleteRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleRequest.Merge(m, src)
}
func (m *DeleteRoleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleRequest.Size(m)
}
func (m *DeleteRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleRequest proto.InternalMessageInfo

func (m *DeleteRoleRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteRoleResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleResponse) Reset()         { *m = DeleteRoleResponse{} }
func (m *DeleteRoleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleResponse) ProtoMessage()    {}
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{10}
}
func (m *DeleteRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleResponse.Unmarshal(m, b)
}
func (m *DeleteRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleResponse.Merge(m, src)
}
func (m *DeleteRoleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleResponse.Size(m)
}
func (m *DeleteRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleResponse proto.InternalMessageInfo

func (m *DeleteRoleResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *DeleteRoleResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *DeleteRoleResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type GetUserRolesRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRolesRequest) Reset()         { *m = GetUserRolesRequest{} }
func (m *GetUserRolesRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRolesRequest) ProtoMessage()    {}
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{11}
}
func (m *GetUserRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRolesRequest.Unmarshal(m, b)
}
func (m *GetUserRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRolesRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRolesRequest.Merge(m, src)
}
func (m *GetUserRolesRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRolesRequest.Size(m)
}
func (m *GetUserRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRolesRequest proto.InternalMessageInfo

func (m *GetUserRolesRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type GetUserRolesResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Roles                []uint32 `protobuf:"varint,4,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRolesResponse) Reset()         { *m = GetUserRolesResponse{} }
func (m *GetUserRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserRolesResponse) ProtoMessage()    {}
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{12}
}
func (m *GetUserRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRolesResponse.Unmarshal(m, b)
}
func (m *GetUserRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetUserRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRolesResponse.Merge(m, src)
}
func (m *GetUserRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserRolesResponse.Size(m)
}
func (m *GetUserRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRolesResponse proto.InternalMessageInfo

func (m *GetUserRolesResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetUserRolesResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetUserRolesResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetUserRolesResponse) GetRoles() []uint32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetRoleUsersRequest struct {
	RoleID               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleUsersRequest) Reset()         { *m = GetRoleUsersRequest{} }
func (m *GetRoleUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleUsersRequest) ProtoMessage()    {}
func (*GetRoleUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{13}
}
func (m *GetRoleUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleUsersRequest.Unmarshal(m, b)
}
func (m *GetRoleUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetRoleUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleUsersRequest.Merge(m, src)
}
func (m *GetRoleUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleUsersRequest.Size(m)
}
func (m *GetRoleUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleUsersRequest proto.InternalMessageInfo

func (m *GetRoleUsersRequest) GetRoleID() uint32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type GetRoleUsersResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Domain               []string `protobuf:"bytes,4,rep,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleUsersResponse) Reset()         { *m = GetRoleUsersResponse{} }
func (m *GetRoleUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoleUsersResponse) ProtoMessage()    {}
func (*GetRoleUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{14}
}
func (m *GetRoleUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleUsersResponse.Unmarshal(m, b)
}
func (m *GetRoleUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetRoleUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleUsersResponse.Merge(m, src)
}
func (m *GetRoleUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoleUsersResponse.Size(m)
}
func (m *GetRoleUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleUsersResponse proto.InternalMessageInfo

func (m *GetRoleUsersResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetRoleUsersResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetRoleUsersResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *GetRoleUsersResponse) GetDomain() []string {
	if m != nil {
		return m.Domain
	}
	return nil
}

type SetUserRoleRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	RoleIds              []uint32 `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserRoleRequest) Reset()         { *m = SetUserRoleRequest{} }
func (m *SetUserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserRoleRequest) ProtoMessage()    {}
func (*SetUserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{15}
}
func (m *SetUserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserRoleRequest.Unmarshal(m, b)
}
func (m *SetUserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserRoleRequest.Marshal(b, m, deterministic)
}
func (m *SetUserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserRoleRequest.Merge(m, src)
}
func (m *SetUserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserRoleRequest.Size(m)
}
func (m *SetUserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserRoleRequest proto.InternalMessageInfo

func (m *SetUserRoleRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SetUserRoleRequest) GetRoleIds() []uint32 {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

type SetUserRoleResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserRoleResponse) Reset()         { *m = SetUserRoleResponse{} }
func (m *SetUserRoleResponse) String() string { return proto.CompactTextString(m) }
func (*SetUserRoleResponse) ProtoMessage()    {}
func (*SetUserRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{16}
}
func (m *SetUserRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserRoleResponse.Unmarshal(m, b)
}
func (m *SetUserRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserRoleResponse.Marshal(b, m, deterministic)
}
func (m *SetUserRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserRoleResponse.Merge(m, src)
}
func (m *SetUserRoleResponse) XXX_Size() int {
	return xxx_messageInfo_SetUserRoleResponse.Size(m)
}
func (m *SetUserRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserRoleResponse proto.InternalMessageInfo

func (m *SetUserRoleResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *SetUserRoleResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *SetUserRoleResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type SetRoleUserRequest struct {
	RoleID               uint32   `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserIDs              []uint32 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoleUserRequest) Reset()         { *m = SetRoleUserRequest{} }
func (m *SetRoleUserRequest) String() string { return proto.CompactTextString(m) }
func (*SetRoleUserRequest) ProtoMessage()    {}
func (*SetRoleUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{17}
}
func (m *SetRoleUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoleUserRequest.Unmarshal(m, b)
}
func (m *SetRoleUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoleUserRequest.Marshal(b, m, deterministic)
}
func (m *SetRoleUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoleUserRequest.Merge(m, src)
}
func (m *SetRoleUserRequest) XXX_Size() int {
	return xxx_messageInfo_SetRoleUserRequest.Size(m)
}
func (m *SetRoleUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoleUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoleUserRequest proto.InternalMessageInfo

func (m *SetRoleUserRequest) GetRoleID() uint32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *SetRoleUserRequest) GetUserIDs() []uint32 {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type SetRoleUserResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoleUserResponse) Reset()         { *m = SetRoleUserResponse{} }
func (m *SetRoleUserResponse) String() string { return proto.CompactTextString(m) }
func (*SetRoleUserResponse) ProtoMessage()    {}
func (*SetRoleUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e0c882973b81e40, []int{18}
}
func (m *SetRoleUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoleUserResponse.Unmarshal(m, b)
}
func (m *SetRoleUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoleUserResponse.Marshal(b, m, deterministic)
}
func (m *SetRoleUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoleUserResponse.Merge(m, src)
}
func (m *SetRoleUserResponse) XXX_Size() int {
	return xxx_messageInfo_SetRoleUserResponse.Size(m)
}
func (m *SetRoleUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoleUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoleUserResponse proto.InternalMessageInfo

func (m *SetRoleUserResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *SetRoleUserResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *SetRoleUserResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*RoleDetail)(nil), "pb.RoleDetail")
	proto.RegisterType((*GetRolesRequest)(nil), "pb.GetRolesRequest")
	proto.RegisterType((*GetRolesResponse)(nil), "pb.GetRolesResponse")
	proto.RegisterType((*GetRoleDetailRequest)(nil), "pb.GetRoleDetailRequest")
	proto.RegisterType((*GetRoleDetailResponse)(nil), "pb.GetRoleDetailResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "pb.CreateRoleRequest")
	proto.RegisterType((*CreateRoleResponse)(nil), "pb.CreateRoleResponse")
	proto.RegisterType((*UpdateRoleRequest)(nil), "pb.UpdateRoleRequest")
	proto.RegisterType((*UpdateRoleResponse)(nil), "pb.UpdateRoleResponse")
	proto.RegisterType((*DeleteRoleRequest)(nil), "pb.DeleteRoleRequest")
	proto.RegisterType((*DeleteRoleResponse)(nil), "pb.DeleteRoleResponse")
	proto.RegisterType((*GetUserRolesRequest)(nil), "pb.GetUserRolesRequest")
	proto.RegisterType((*GetUserRolesResponse)(nil), "pb.GetUserRolesResponse")
	proto.RegisterType((*GetRoleUsersRequest)(nil), "pb.GetRoleUsersRequest")
	proto.RegisterType((*GetRoleUsersResponse)(nil), "pb.GetRoleUsersResponse")
	proto.RegisterType((*SetUserRoleRequest)(nil), "pb.SetUserRoleRequest")
	proto.RegisterType((*SetUserRoleResponse)(nil), "pb.SetUserRoleResponse")
	proto.RegisterType((*SetRoleUserRequest)(nil), "pb.SetRoleUserRequest")
	proto.RegisterType((*SetRoleUserResponse)(nil), "pb.SetRoleUserResponse")
}

func init() { proto.RegisterFile("role_action.proto", fileDescriptor_1e0c882973b81e40) }

var fileDescriptor_1e0c882973b81e40 = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0x4e, 0xdb, 0x4a,
	0x14, 0x95, 0x4d, 0x30, 0x61, 0x47, 0x5c, 0x62, 0x38, 0xc8, 0x80, 0x90, 0x73, 0x4c, 0x40, 0x0e,
	0x28, 0xc9, 0xd1, 0xe9, 0x13, 0x97, 0x5e, 0x08, 0x91, 0x10, 0x95, 0xe0, 0xc1, 0x15, 0x2f, 0x90,
	0x8b, 0x26, 0x78, 0x14, 0x59, 0x4a, 0x32, 0xae, 0xc7, 0x80, 0xd4, 0x16, 0xfe, 0xa2, 0xea, 0x73,
	0xfb, 0x07, 0xfd, 0x91, 0x7e, 0x02, 0x48, 0x91, 0xfa, 0x1f, 0xd5, 0xcc, 0x98, 0xd8, 0x86, 0x20,
	0x42, 0x1f, 0xfc, 0x36, 0xde, 0xb3, 0x66, 0x66, 0xaf, 0xbd, 0xd7, 0x2c, 0x0f, 0x64, 0x3d, 0xd2,
	0xc1, 0x4d, 0x74, 0xee, 0x3b, 0xa4, 0x57, 0x72, 0x3d, 0xe2, 0x13, 0x55, 0x76, 0x5b, 0x4b, 0x33,
	0x97, 0xa8, 0xe3, 0xd8, 0xc8, 0x27, 0x9e, 0x08, 0x2e, 0xcd, 0xb7, 0x49, 0x9b, 0xf0, 0x61, 0x99,
	0x8d, 0x44, 0xd4, 0xf8, 0x2d, 0x01, 0x58, 0xa4, 0x83, 0xab, 0xd8, 0x47, 0x4e, 0x47, 0x5d, 0x85,
	0x09, 0xbe, 0x9d, 0x63, 0x6b, 0x52, 0x4e, 0x32, 0xa7, 0x2a, 0xd0, 0xbf, 0xd5, 0x15, 0x06, 0x38,
	0xac, 0x5a, 0x0a, 0x9b, 0x3a, 0xb4, 0xd5, 0x65, 0x98, 0xe4, 0xa0, 0x1e, 0xea, 0x62, 0x4d, 0xce,
	0x49, 0xe6, 0xa4, 0x95, 0x66, 0x81, 0x63, 0xd4, 0xc5, 0x6a, 0x01, 0x66, 0xf9, 0xa4, 0x8d, 0xe9,
	0xb9, 0xe7, 0xb8, 0x2c, 0x2b, 0x6d, 0x8c, 0x63, 0x66, 0x3c, 0x7e, 0xce, 0x20, 0xac, 0x96, 0x60,
	0x8e, 0x43, 0xbb, 0xa8, 0x87, 0xda, 0xd8, 0x6b, 0xda, 0xa4, 0x8b, 0x9c, 0x9e, 0x96, 0xe2, 0x68,
	0x4e, 0xeb, 0x48, 0xcc, 0x54, 0xf9, 0x84, 0xba, 0x02, 0x20, 0xb8, 0x76, 0x1c, 0x44, 0xb5, 0x71,
	0x0e, 0xe3, 0x99, 0xec, 0xb1, 0x00, 0x4b, 0xcb, 0xa1, 0xbc, 0x10, 0x97, 0x58, 0x53, 0x72, 0x92,
	0x99, 0xb6, 0xd2, 0x0e, 0xdd, 0xe3, 0xdf, 0xc6, 0x16, 0xcc, 0x1c, 0x60, 0x9f, 0x11, 0xa1, 0x16,
	0xfe, 0x78, 0x81, 0xa9, 0xaf, 0xae, 0x43, 0x3a, 0xe0, 0x4a, 0x39, 0xd9, 0xc9, 0x4a, 0xa6, 0x7f,
	0xab, 0x4f, 0x08, 0xb2, 0xd4, 0x9a, 0x10, 0x6c, 0xa9, 0xf1, 0x5d, 0x82, 0xd9, 0x70, 0x2d, 0x75,
	0x49, 0x8f, 0x62, 0x55, 0x87, 0x0c, 0xf5, 0x91, 0x7f, 0x41, 0x9b, 0xe7, 0xc4, 0xc6, 0x62, 0xbd,
	0x05, 0x22, 0xb4, 0x4f, 0x6c, 0x0e, 0xf0, 0x30, 0xa2, 0xa4, 0x27, 0x00, 0xa2, 0x4c, 0x20, 0x42,
	0x1c, 0xb0, 0x06, 0xd3, 0x01, 0xa0, 0x8b, 0x29, 0x45, 0x6d, 0x1c, 0x94, 0x69, 0x4a, 0x44, 0x8f,
	0x44, 0x50, 0xcd, 0xc3, 0x38, 0x4b, 0x84, 0x6a, 0xa9, 0xdc, 0x98, 0x99, 0xf9, 0x7f, 0xba, 0xe4,
	0xb6, 0x4a, 0x61, 0xc3, 0x2c, 0x31, 0x69, 0xec, 0xc0, 0x7c, 0x90, 0x62, 0x10, 0x0f, 0x38, 0x8e,
	0xd2, 0x4f, 0xe3, 0xa7, 0x04, 0xff, 0x3c, 0x58, 0x9d, 0x34, 0xcb, 0x32, 0x64, 0x02, 0xd5, 0xb0,
	0xf3, 0xb9, 0x04, 0x1e, 0x73, 0x05, 0x6f, 0x30, 0x36, 0x7e, 0xc9, 0x90, 0xdd, 0xf7, 0x30, 0xf2,
	0x31, 0x03, 0xdc, 0xd3, 0xdd, 0x8d, 0x2a, 0x53, 0xf4, 0x54, 0xef, 0xdf, 0xe9, 0xcb, 0xb0, 0xd8,
	0x30, 0xcf, 0x1a, 0xff, 0xbe, 0x5b, 0xcd, 0xaf, 0xad, 0x6f, 0x6c, 0xbe, 0xbe, 0x79, 0xbb, 0xb3,
	0xbd, 0xfb, 0xe6, 0xf3, 0x75, 0x7d, 0xa3, 0x90, 0x8f, 0x48, 0xf7, 0xfd, 0x10, 0xe9, 0xca, 0xa3,
	0x6d, 0xf2, 0x48, 0xdb, 0xcd, 0xe1, 0xda, 0xe6, 0xe4, 0x2b, 0xe5, 0xfe, 0x9d, 0xbe, 0x09, 0x85,
	0x86, 0xd9, 0x38, 0xab, 0x5d, 0x7d, 0xa9, 0x95, 0xeb, 0x05, 0xf3, 0xac, 0xd6, 0xac, 0x15, 0x6b,
	0x65, 0x54, 0xfc, 0xb4, 0x57, 0x3c, 0xfd, 0xaf, 0xb8, 0x55, 0xcb, 0xd5, 0x37, 0x58, 0xf4, 0xaa,
	0x9e, 0x2f, 0xe4, 0x87, 0x5d, 0x86, 0xe3, 0xd8, 0x65, 0x48, 0xfd, 0xdd, 0xbe, 0xe1, 0xed, 0x31,
	0x7e, 0x48, 0xa0, 0x46, 0x0b, 0x1a, 0x28, 0x60, 0x24, 0x43, 0x78, 0x20, 0x13, 0xf9, 0x39, 0x99,
	0x8c, 0x8d, 0x20, 0x93, 0xd4, 0x10, 0x99, 0x18, 0x77, 0x12, 0x64, 0x4f, 0x5c, 0xfb, 0x41, 0xd7,
	0x17, 0x40, 0x1e, 0xa4, 0xa7, 0xf4, 0x6f, 0x75, 0xf9, 0xb0, 0x6a, 0xc9, 0x8e, 0x1d, 0x37, 0x04,
	0x39, 0x6e, 0x08, 0x2f, 0xf1, 0xa9, 0x95, 0xc7, 0xa5, 0x8e, 0xfa, 0xce, 0x13, 0x36, 0x36, 0xfe,
	0x94, 0x8d, 0xc5, 0xec, 0x53, 0x89, 0xdb, 0xa7, 0x71, 0x0d, 0x6a, 0x94, 0x60, 0xc2, 0xf7, 0xd0,
	0xd8, 0x84, 0x6c, 0x15, 0x77, 0xf0, 0x48, 0xf5, 0x65, 0xb9, 0x46, 0xc1, 0x49, 0xe7, 0x5a, 0x84,
	0xb9, 0x03, 0xec, 0x9f, 0x50, 0xec, 0xc5, 0x6c, 0x7d, 0x01, 0x94, 0xa0, 0x03, 0xe2, 0xe8, 0xe0,
	0xcb, 0xf8, 0x2a, 0x71, 0x8f, 0x8c, 0xe0, 0x93, 0x36, 0xb9, 0xf9, 0xa8, 0x95, 0x4f, 0xdd, 0x5b,
	0xf7, 0x36, 0xa7, 0xc1, 0x52, 0x62, 0xa9, 0xd1, 0x17, 0x39, 0xf7, 0x37, 0x69, 0xe0, 0xfb, 0xc1,
	0xe2, 0xa4, 0x39, 0x85, 0xd5, 0x66, 0xa4, 0xc2, 0x6a, 0x1f, 0x80, 0xfa, 0x21, 0x2c, 0xf6, 0x33,
	0xbd, 0x51, 0x17, 0x23, 0xbf, 0x62, 0x99, 0x17, 0x67, 0xf0, 0xf7, 0xbd, 0x81, 0xb9, 0xd8, 0x46,
	0x49, 0xab, 0x0c, 0x71, 0x22, 0xf7, 0x15, 0x7e, 0x49, 0x77, 0xd8, 0x03, 0xe3, 0x82, 0x62, 0x2f,
	0x64, 0x25, 0x1e, 0x18, 0x6c, 0x1f, 0xfe, 0xc0, 0x60, 0x93, 0x21, 0xc5, 0xf0, 0x88, 0x84, 0x29,
	0x56, 0x94, 0xd3, 0x54, 0x69, 0xc7, 0x6d, 0xb5, 0x14, 0xfe, 0x24, 0x7c, 0xf5, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x15, 0x67, 0xb4, 0xc0, 0x52, 0x0a, 0x00, 0x00,
}
