// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user_action.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UserLoginRequest) Validate() error {
	return nil
}
func (this *UserLoginResponse) Validate() error {
	return nil
}
func (this *UserRegisterRequest) Validate() error {
	return nil
}
func (this *UserRegisterResponse) Validate() error {
	return nil
}
func (this *UserLogoutRequest) Validate() error {
	return nil
}
func (this *UserLogoutResponse) Validate() error {
	return nil
}
func (this *UserDetails) Validate() error {
	return nil
}
func (this *GetUserDetailRequest) Validate() error {
	return nil
}
func (this *GetUserDetailResponse) Validate() error {
	if this.UserDetails != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserDetails); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserDetails", err)
		}
	}
	return nil
}
func (this *SearchUserRequest) Validate() error {
	return nil
}
func (this *User) Validate() error {
	return nil
}
func (this *SearchUserResponse) Validate() error {
	for _, item := range this.UserDetails {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("UserDetails", err)
			}
		}
	}
	return nil
}
func (this *SetUserDetailRequest) Validate() error {
	return nil
}
func (this *SetUserDetailResponse) Validate() error {
	return nil
}
func (this *DeleteUserDetailRequest) Validate() error {
	return nil
}
func (this *DeleteUserDetailResponse) Validate() error {
	return nil
}
func (this *VerifyTokenRequest) Validate() error {
	return nil
}
func (this *VerifyTokenResponse) Validate() error {
	return nil
}
