// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user_action.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{0}
}
func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Paseto               string   `protobuf:"bytes,4,opt,name=paseto,proto3" json:"paseto,omitempty"`
	Jwt                  string   `protobuf:"bytes,5,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{1}
}
func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *UserLoginResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *UserLoginResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *UserLoginResponse) GetPaseto() string {
	if m != nil {
		return m.Paseto
	}
	return ""
}

func (m *UserLoginResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type UserRegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	FullName             string   `protobuf:"bytes,7,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{2}
}
func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegisterRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserRegisterRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserRegisterRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserRegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UserRegisterResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Paseto               string   `protobuf:"bytes,4,opt,name=paseto,proto3" json:"paseto,omitempty"`
	Jwt                  string   `protobuf:"bytes,5,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{3}
}
func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *UserRegisterResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *UserRegisterResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func (m *UserRegisterResponse) GetPaseto() string {
	if m != nil {
		return m.Paseto
	}
	return ""
}

func (m *UserRegisterResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type UserLogoutRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogoutRequest) Reset()         { *m = UserLogoutRequest{} }
func (m *UserLogoutRequest) String() string { return proto.CompactTextString(m) }
func (*UserLogoutRequest) ProtoMessage()    {}
func (*UserLogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{4}
}
func (m *UserLogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogoutRequest.Unmarshal(m, b)
}
func (m *UserLogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogoutRequest.Marshal(b, m, deterministic)
}
func (m *UserLogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogoutRequest.Merge(m, src)
}
func (m *UserLogoutRequest) XXX_Size() int {
	return xxx_messageInfo_UserLogoutRequest.Size(m)
}
func (m *UserLogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogoutRequest proto.InternalMessageInfo

func (m *UserLogoutRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UserLogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserLogoutResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogoutResponse) Reset()         { *m = UserLogoutResponse{} }
func (m *UserLogoutResponse) String() string { return proto.CompactTextString(m) }
func (*UserLogoutResponse) ProtoMessage()    {}
func (*UserLogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{5}
}
func (m *UserLogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogoutResponse.Unmarshal(m, b)
}
func (m *UserLogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogoutResponse.Marshal(b, m, deterministic)
}
func (m *UserLogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogoutResponse.Merge(m, src)
}
func (m *UserLogoutResponse) XXX_Size() int {
	return xxx_messageInfo_UserLogoutResponse.Size(m)
}
func (m *UserLogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogoutResponse proto.InternalMessageInfo

func (m *UserLogoutResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *UserLogoutResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *UserLogoutResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type UserDetails struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Domain               string   `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`
	IsActive             bool     `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{6}
}
func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserDetails) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserDetails) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserDetails) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserDetails) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserDetails) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UserDetails) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type GetUserDetailRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDetailRequest) Reset()         { *m = GetUserDetailRequest{} }
func (m *GetUserDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserDetailRequest) ProtoMessage()    {}
func (*GetUserDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{7}
}
func (m *GetUserDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDetailRequest.Unmarshal(m, b)
}
func (m *GetUserDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetUserDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDetailRequest.Merge(m, src)
}
func (m *GetUserDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserDetailRequest.Size(m)
}
func (m *GetUserDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDetailRequest proto.InternalMessageInfo

func (m *GetUserDetailRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type GetUserDetailResponse struct {
	UserDetails          *UserDetails `protobuf:"bytes,1,opt,name=user_details,json=userDetails,proto3" json:"user_details,omitempty"`
	StatusCode           string       `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string       `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string       `protobuf:"bytes,4,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserDetailResponse) Reset()         { *m = GetUserDetailResponse{} }
func (m *GetUserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserDetailResponse) ProtoMessage()    {}
func (*GetUserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{8}
}
func (m *GetUserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDetailResponse.Unmarshal(m, b)
}
func (m *GetUserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetUserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDetailResponse.Merge(m, src)
}
func (m *GetUserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserDetailResponse.Size(m)
}
func (m *GetUserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDetailResponse proto.InternalMessageInfo

func (m *GetUserDetailResponse) GetUserDetails() *UserDetails {
	if m != nil {
		return m.UserDetails
	}
	return nil
}

func (m *GetUserDetailResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *GetUserDetailResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *GetUserDetailResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type SearchUserRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserRequest) Reset()         { *m = SearchUserRequest{} }
func (m *SearchUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserRequest) ProtoMessage()    {}
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{9}
}
func (m *SearchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserRequest.Unmarshal(m, b)
}
func (m *SearchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserRequest.Marshal(b, m, deterministic)
}
func (m *SearchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserRequest.Merge(m, src)
}
func (m *SearchUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserRequest.Size(m)
}
func (m *SearchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserRequest proto.InternalMessageInfo

func (m *SearchUserRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	EmployeeId           string   `protobuf:"bytes,4,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	UserId               uint32   `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{10}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *User) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *User) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SearchUserResponse struct {
	UserDetails          []*UserDetails `protobuf:"bytes,1,rep,name=user_details,json=userDetails,proto3" json:"user_details,omitempty"`
	StatusCode           string         `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string         `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string         `protobuf:"bytes,4,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchUserResponse) Reset()         { *m = SearchUserResponse{} }
func (m *SearchUserResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUserResponse) ProtoMessage()    {}
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{11}
}
func (m *SearchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserResponse.Unmarshal(m, b)
}
func (m *SearchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserResponse.Marshal(b, m, deterministic)
}
func (m *SearchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserResponse.Merge(m, src)
}
func (m *SearchUserResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUserResponse.Size(m)
}
func (m *SearchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserResponse proto.InternalMessageInfo

func (m *SearchUserResponse) GetUserDetails() []*UserDetails {
	if m != nil {
		return m.UserDetails
	}
	return nil
}

func (m *SearchUserResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *SearchUserResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *SearchUserResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type SetUserDetailRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Domain               string   `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`
	IsActive             bool     `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserDetailRequest) Reset()         { *m = SetUserDetailRequest{} }
func (m *SetUserDetailRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserDetailRequest) ProtoMessage()    {}
func (*SetUserDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{12}
}
func (m *SetUserDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserDetailRequest.Unmarshal(m, b)
}
func (m *SetUserDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserDetailRequest.Marshal(b, m, deterministic)
}
func (m *SetUserDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserDetailRequest.Merge(m, src)
}
func (m *SetUserDetailRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserDetailRequest.Size(m)
}
func (m *SetUserDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserDetailRequest proto.InternalMessageInfo

func (m *SetUserDetailRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *SetUserDetailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SetUserDetailRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SetUserDetailRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SetUserDetailRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SetUserDetailRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SetUserDetailRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SetUserDetailRequest) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type SetUserDetailResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserDetailResponse) Reset()         { *m = SetUserDetailResponse{} }
func (m *SetUserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*SetUserDetailResponse) ProtoMessage()    {}
func (*SetUserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{13}
}
func (m *SetUserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserDetailResponse.Unmarshal(m, b)
}
func (m *SetUserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserDetailResponse.Marshal(b, m, deterministic)
}
func (m *SetUserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserDetailResponse.Merge(m, src)
}
func (m *SetUserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_SetUserDetailResponse.Size(m)
}
func (m *SetUserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserDetailResponse proto.InternalMessageInfo

func (m *SetUserDetailResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *SetUserDetailResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *SetUserDetailResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type DeleteUserDetailRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserDetailRequest) Reset()         { *m = DeleteUserDetailRequest{} }
func (m *DeleteUserDetailRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserDetailRequest) ProtoMessage()    {}
func (*DeleteUserDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{14}
}
func (m *DeleteUserDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserDetailRequest.Unmarshal(m, b)
}
func (m *DeleteUserDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserDetailRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserDetailRequest.Merge(m, src)
}
func (m *DeleteUserDetailRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserDetailRequest.Size(m)
}
func (m *DeleteUserDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserDetailRequest proto.InternalMessageInfo

func (m *DeleteUserDetailRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *DeleteUserDetailRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type DeleteUserDetailResponse struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,3,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserDetailResponse) Reset()         { *m = DeleteUserDetailResponse{} }
func (m *DeleteUserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserDetailResponse) ProtoMessage()    {}
func (*DeleteUserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{15}
}
func (m *DeleteUserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserDetailResponse.Unmarshal(m, b)
}
func (m *DeleteUserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserDetailResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserDetailResponse.Merge(m, src)
}
func (m *DeleteUserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserDetailResponse.Size(m)
}
func (m *DeleteUserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserDetailResponse proto.InternalMessageInfo

func (m *DeleteUserDetailResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *DeleteUserDetailResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *DeleteUserDetailResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

type VerifyTokenRequest struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{16}
}
func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

func (m *VerifyTokenRequest) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *VerifyTokenRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type VerifyTokenResponse struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	StatusCode           string   `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode           string   `protobuf:"bytes,4,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage        string   `protobuf:"bytes,5,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResponse) Reset()         { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()    {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54379ed0225a565c, []int{17}
}
func (m *VerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResponse.Unmarshal(m, b)
}
func (m *VerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResponse.Merge(m, src)
}
func (m *VerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResponse.Size(m)
}
func (m *VerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResponse proto.InternalMessageInfo

func (m *VerifyTokenResponse) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *VerifyTokenResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *VerifyTokenResponse) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *VerifyTokenResponse) GetReasonMessage() string {
	if m != nil {
		return m.ReasonMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLoginRequest)(nil), "pb.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "pb.UserLoginResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "pb.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "pb.UserRegisterResponse")
	proto.RegisterType((*UserLogoutRequest)(nil), "pb.UserLogoutRequest")
	proto.RegisterType((*UserLogoutResponse)(nil), "pb.UserLogoutResponse")
	proto.RegisterType((*UserDetails)(nil), "pb.UserDetails")
	proto.RegisterType((*GetUserDetailRequest)(nil), "pb.GetUserDetailRequest")
	proto.RegisterType((*GetUserDetailResponse)(nil), "pb.GetUserDetailResponse")
	proto.RegisterType((*SearchUserRequest)(nil), "pb.SearchUserRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*SearchUserResponse)(nil), "pb.SearchUserResponse")
	proto.RegisterType((*SetUserDetailRequest)(nil), "pb.SetUserDetailRequest")
	proto.RegisterType((*SetUserDetailResponse)(nil), "pb.SetUserDetailResponse")
	proto.RegisterType((*DeleteUserDetailRequest)(nil), "pb.DeleteUserDetailRequest")
	proto.RegisterType((*DeleteUserDetailResponse)(nil), "pb.DeleteUserDetailResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "pb.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "pb.VerifyTokenResponse")
}

func init() { proto.RegisterFile("user_action.proto", fileDescriptor_54379ed0225a565c) }

var fileDescriptor_54379ed0225a565c = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0x67, 0x36, 0x9b, 0xfd, 0xf3, 0xb6, 0xd5, 0x36, 0x4d, 0x6d, 0x68, 0x91, 0x6a, 0x44, 0x10,
	0x84, 0x15, 0xea, 0x45, 0xf0, 0xd4, 0x5a, 0x94, 0x82, 0xf6, 0xb0, 0xd5, 0x1e, 0xbc, 0x2c, 0xb3,
	0xcd, 0xeb, 0x76, 0x34, 0xc9, 0xc4, 0xcc, 0xc4, 0xd2, 0x83, 0x20, 0xf8, 0x09, 0xbc, 0xf8, 0x11,
	0x04, 0x8f, 0x82, 0x9f, 0xc7, 0x83, 0x27, 0x4f, 0x5e, 0xbd, 0xca, 0xcc, 0x24, 0x6d, 0xb2, 0xdd,
	0xed, 0xf6, 0xb4, 0x14, 0x4f, 0x9b, 0xf7, 0xe6, 0xbd, 0xd9, 0xf7, 0xfb, 0x93, 0x99, 0xc0, 0x62,
	0x26, 0x30, 0xed, 0xd3, 0x03, 0xc9, 0x78, 0xdc, 0x4d, 0x52, 0x2e, 0xb9, 0x53, 0x4b, 0x06, 0xab,
	0xee, 0x90, 0x0f, 0xb9, 0x0e, 0x1f, 0xa8, 0x27, 0xb3, 0xe2, 0x3f, 0x85, 0x85, 0x57, 0x02, 0xd3,
	0xe7, 0x7c, 0xc8, 0xe2, 0x1e, 0xbe, 0xcb, 0x50, 0x48, 0xe7, 0x06, 0x34, 0x02, 0x1e, 0x51, 0x16,
	0x7b, 0xe4, 0x16, 0xb9, 0xd7, 0xee, 0xe5, 0x91, 0xb3, 0x0a, 0xad, 0x84, 0x0a, 0x71, 0xcc, 0xd3,
	0xc0, 0xab, 0xe9, 0x95, 0xd3, 0xd8, 0xff, 0x4a, 0x60, 0xb1, 0xb4, 0x91, 0x48, 0x78, 0x2c, 0xd0,
	0x59, 0x87, 0x8e, 0x90, 0x54, 0x66, 0xa2, 0x7f, 0xc0, 0x03, 0xcc, 0xb7, 0x03, 0x93, 0x7a, 0xc2,
	0x03, 0x5d, 0x90, 0x22, 0x15, 0x3c, 0x36, 0x05, 0x66, 0x57, 0x30, 0x29, 0x5d, 0x70, 0x17, 0xae,
	0xe5, 0x05, 0x11, 0x0a, 0x41, 0x87, 0xe8, 0x59, 0xba, 0x66, 0xde, 0x64, 0x5f, 0x98, 0xa4, 0x1a,
	0x39, 0xa1, 0x02, 0x25, 0xf7, 0xea, 0x66, 0x64, 0x13, 0x39, 0x0b, 0x60, 0xbd, 0x39, 0x96, 0x9e,
	0xad, 0x93, 0xea, 0xd1, 0xff, 0x4d, 0x60, 0x49, 0x0d, 0xda, 0xc3, 0x21, 0x13, 0x52, 0xfd, 0x1a,
	0xd0, 0x2e, 0xd8, 0x18, 0x51, 0x16, 0xe6, 0x43, 0x9a, 0xa0, 0x44, 0x45, 0x6d, 0x22, 0x15, 0x56,
	0x95, 0x0a, 0xe7, 0x26, 0xc0, 0x21, 0x4b, 0x85, 0xec, 0xc7, 0x34, 0xc2, 0x7c, 0x9e, 0xb6, 0xce,
	0xec, 0xd2, 0x08, 0x9d, 0x35, 0x68, 0x87, 0xb4, 0x58, 0x35, 0x83, 0xb5, 0x54, 0x42, 0x2f, 0x7a,
	0xd0, 0xa4, 0x41, 0x90, 0xa2, 0x10, 0x5e, 0x43, 0x2f, 0x15, 0xa1, 0x6a, 0x3b, 0xcc, 0xc2, 0xd0,
	0xb4, 0x35, 0x4d, 0x9b, 0x4a, 0xe8, 0x36, 0x17, 0xec, 0xe4, 0x88, 0xc7, 0xe8, 0xb5, 0xcc, 0xf0,
	0x3a, 0xf0, 0xbf, 0x11, 0x70, 0xab, 0x50, 0xaf, 0xae, 0x2c, 0x9b, 0xa7, 0xf6, 0xe1, 0x99, 0x9c,
	0x66, 0x44, 0x17, 0x6c, 0xc9, 0xdf, 0x62, 0x21, 0x8a, 0x09, 0xfc, 0x0f, 0xe0, 0x94, 0xb7, 0x98,
	0x31, 0x56, 0xff, 0x0f, 0x81, 0x8e, 0xfa, 0xff, 0x6d, 0x94, 0x94, 0x85, 0x23, 0x82, 0x91, 0xf3,
	0x82, 0x19, 0xb7, 0xd5, 0xca, 0x6e, 0xab, 0x3a, 0xc7, 0xba, 0xd0, 0x39, 0xf5, 0xc9, 0xce, 0xb1,
	0xab, 0xce, 0xb9, 0x0d, 0x73, 0xda, 0x0f, 0xfd, 0x38, 0x8b, 0x06, 0x98, 0xe6, 0xc6, 0xea, 0xe8,
	0xdc, 0xae, 0x4e, 0x95, 0x88, 0x6e, 0x56, 0x88, 0x5e, 0x83, 0x36, 0x13, 0xfa, 0x28, 0x79, 0x6f,
	0xbc, 0xd5, 0xea, 0xb5, 0x98, 0xd8, 0xd4, 0xb1, 0xdf, 0x05, 0xf7, 0x19, 0xca, 0x33, 0xc8, 0x53,
	0x54, 0xf3, 0x7f, 0x10, 0x58, 0x1e, 0x69, 0xc8, 0x35, 0xda, 0x80, 0x39, 0x7d, 0x66, 0x05, 0x86,
	0x3a, 0xdd, 0xd7, 0xd9, 0xb8, 0xde, 0x4d, 0x06, 0xdd, 0x12, 0xa3, 0xbd, 0x4e, 0x56, 0xa2, 0x77,
	0x44, 0xd7, 0xda, 0x34, 0x5d, 0xad, 0x4b, 0xe8, 0x5a, 0x1f, 0xa7, 0xeb, 0x7d, 0x58, 0xdc, 0x43,
	0x9a, 0x1e, 0x1c, 0x99, 0x57, 0xe9, 0x62, 0x8c, 0x9f, 0x09, 0xd4, 0x55, 0xdd, 0x84, 0xe3, 0x64,
	0x54, 0x8a, 0xda, 0x45, 0x52, 0x58, 0x15, 0x29, 0xd6, 0xa1, 0x83, 0x51, 0x12, 0xf2, 0x13, 0xc4,
	0x3e, 0x0b, 0xf2, 0x51, 0xa1, 0x48, 0xed, 0x04, 0xce, 0x0a, 0x34, 0x35, 0x89, 0x2c, 0xd0, 0x06,
	0x98, 0xef, 0x35, 0x54, 0xb8, 0x13, 0xf8, 0xdf, 0x09, 0x38, 0x65, 0x04, 0x13, 0x49, 0xb7, 0xae,
	0x0e, 0xe9, 0x7f, 0x09, 0xb8, 0x7b, 0xe3, 0xcc, 0xf5, 0xdf, 0xbf, 0x55, 0x1f, 0x09, 0x2c, 0xef,
	0x8d, 0x7d, 0x4b, 0x66, 0x76, 0x92, 0xed, 0xc3, 0xca, 0x36, 0x86, 0x28, 0xf1, 0x3c, 0xfd, 0x77,
	0xce, 0x4c, 0xa6, 0xfe, 0xdf, 0xde, 0x82, 0x5f, 0x3f, 0xd7, 0x1b, 0xaa, 0x6e, 0x67, 0xbb, 0x30,
	0xdc, 0xa4, 0x4b, 0xd3, 0xff, 0x44, 0xc0, 0x3b, 0xbf, 0xf1, 0xac, 0xd1, 0x3d, 0x02, 0x67, 0x1f,
	0x53, 0x76, 0x78, 0xf2, 0x52, 0xdd, 0x1a, 0x05, 0xb0, 0xfc, 0x46, 0x22, 0xa7, 0x37, 0x92, 0xca,
	0x64, 0xac, 0xf8, 0xd0, 0x51, 0x8f, 0xfe, 0x17, 0x02, 0x4b, 0x95, 0xd6, 0x7c, 0xf4, 0x49, 0xd7,
	0xd4, 0x08, 0x24, 0x6b, 0x1a, 0xa4, 0xfa, 0x25, 0x20, 0xd9, 0x63, 0x20, 0x6d, 0x35, 0x5e, 0xd7,
	0xbb, 0x8f, 0x93, 0xc1, 0xa0, 0xa1, 0xbf, 0xe9, 0x1e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x07,
	0x93, 0x40, 0x09, 0x02, 0x0a, 0x00, 0x00,
}
